### ISSUE TITLE
New version is 7.9.7, but no online

### ISSUE THREAD

**Issue by Pyntux** [fjtrujy/capricornCNFirmware#1]
Sorry but I do not know how to ask you to update firmware package to latest...

Thanks

**Comment by JesusRoMarti** [comment]
Hi, I'm not the one who started the thread, I do not take care of maintenance.

**Comment by fjtrujy** [comment]
Hello,

Sorry guys I have been on holidays, I will try to update it tomorrow.

Thanks for you collaboration.

**Comment by Pyntux** [comment]
@fjtrujy

Thank you and sorry for bothering you... There will be new china beta rom today, so 7.9.7 is no newest anymore... :)

**Comment by fjtrujy** [comment]
Both updated!!!
Closing issue

**Comment by Pyntux** [comment]
Thank you!
