### ISSUE TITLE
Newer firmware

### ISSUE THREAD

**Issue by maeckha** [fjtrujy/capricornCNFirmware#2]
Hello,
I tried to fix the audio/video problem that comes with LOS on the mi5s.
So I flashed this newest firmware and right after this the Lineage OS build again. 
I got the Error 7 and was asked to flash a newer firmware version which I cannot find. 
Is this the newest one? If not, where can I find it?
Thank you!

**Comment by nuzar** [comment]
https://github.com/XiaomiFirmwareUpdater/firmware_xiaomi_capricorn/releases

**Comment by maeckha** [comment]
You just solved an hours long problem for me. Thank you very much!
